const path = require('path');
const generate = require('../../../../src/index');

module.exports = {
    entry: path.resolve(__dirname, 'test.js'),
    output: {
        path: process.env.outputDir
    },
    plugins: [
        generate({
            file: path.resolve(process.env.outputDir, 'output-a.txt'),
            content: 'Some static content A, generated by: GenerateFileWebpackPlugin'
        }),
        generate({
            file: path.resolve(process.env.outputDir, 'output-b.txt'),
            content: 'Some static content B, generated by: GenerateFileWebpackPlugin'
        })
    ]
};