const path = require('path');
const my_generate = require('../../../../src/index');

module.exports = {
    entry: path.resolve(__dirname, 'test.js'),
    output: {
        path: process.env.outputDir
    },
    plugins: [
        my_generate({
            file: path.resolve(process.env.outputDir, 'output.txt'),
            content:  'Some static content, generated by: GenerateFileWebpackPlugin'
        })
    ]
};