const path = require('path');
const {GenerateFileWebpackPlugin} = require('../../../../src/index');

module.exports = {
    entry: path.resolve(__dirname, 'test.js'),
    output: {
        path: process.env.outputDir
    },
    plugins: [
        new GenerateFileWebpackPlugin({
            file: path.resolve(process.env.outputDir, 'output.txt'),
            content: promiseContentFunction
        })
    ]
};

function promiseContentFunction() {
    return new Promise(function(resolve, reject) {
        setTimeout(() => resolve("Some content, generated by: GenerateFileWebpackPlugin"), 1000);
    });
}