const path = require('path');
const generate = require('../../../../src/index');

module.exports = {
    entry: path.resolve(__dirname, 'test.js'),
    plugins: [
        generate({
            file: 'output.txt',
            content:
                'Some content, generated by: GenerateFileWebpackPlugin'
        })
    ]
};