const path = require('path');
const {GenerateFileWebpackPlugin} = require('../../../../src/index');

module.exports = {
    entry: path.resolve(__dirname, 'test.js'),
    output: {
        path: process.env.outputDir
    },
    plugins: [
        new GenerateFileWebpackPlugin({
            file: path.resolve(process.env.outputDir, 'output.txt'),
            content: new Promise(function(resolve) {
                setTimeout(() => resolve("Some content, generated by: GenerateFileWebpackPlugin"), 1000);
            })
        })
    ]
};
