const path = require('path');
const generate = require('../../../../src/index');

module.exports = {
    entry: path.resolve(__dirname, 'test.js'),
    output: {
        path: process.env.outputDir
    },
    plugins: [
        generate({
            file: '../with-relative-parent-navigation-alt/output.txt',
            content:
                'Some content, generated by: GenerateFileWebpackPlugin'
        })
    ]
};